### ISSUE TITLE
Don't load site icon for incognito tabs

### ISSUE THREAD

**Issue by jscher2000** [lusakasa/saka#28] opened 2018-04-24 01:00 UTC
To prevent private window site icons from being stored in the regular cache, it would be preferable not to load them in the popup. You could use null or with a little more work, replace them with a mask icon (for example, https://design.firefox.com/icons/viewer/ under the "General" category).

When I search in this repository, it seems that a good opportunity to return a null or alternative value for tab.favIconUrl may be in allTabSuggestions() where you could access tab.incognito, but to be honest, I'm having trouble following the code.

Ref. https://discourse.mozilla.org/t/context-of-inline-image-requests-in-extension-page-e-g-a-popup/27932

**Comment by pureooze** [comment] 2018-04-24 01:48
Just want to make sure I am understanding this. The issue is that since the icons are being requested and stored in cache by Saka, other pages will also gain access to it for fingerprinting purposes? Or something else?

And I would agree that allTabSuggestions is a good place to put this logic, but there may need to be some changes in the Suggestion component [here](https://github.com/lusakasa/saka/blob/master/src/saka/Main/Components/SuggestionList/Components/Suggestion/index.js#L30-L42) depending on how we would access the favicon. Since Saka already uses the material icons, I would prefer using something from there that can convey the same message as the mask.

**Comment by jscher2000** [comment] 2018-04-24 02:05
The concern is not about other pages, since I don't think you are inserting the tab history into content. My concern is keeping private browsing data private.

The user may be visiting site X in a private window to keep all evidence of their visit out of Firefox's persistent data stores. When the popup is displayed in a regular window, Firefox caches those site icons in the regular disk cache, not distinguishing that some may have been from a private window. So then the site X icon would appear in the disk cache (with a fresh time stamp on the about:cache page under disk cache), contrary to user expectations.

I wasn't able to discover any way around this, so I suggest not showing the site icon. I think you can use any alternate icon you prefer; your taste probably is better than mine.

**Comment by eejdoowad** [comment] 2018-04-24 02:34
Huh, that's interesting. When querying tabs, Chrome filters incognito tabs while Firefox includes them. 

@jscher2000's suggestion makes sense. To prevent Firefox from caching private tab favicons in non-private disk storage (thus exposing that you've visited certain websites), it's best to show an alternative favicon icon. This can be fixed by modifying the favicon url [here](https://github.com/lusakasa/saka/blob/master/src/suggestion_engine/server/providers/tab.js#L46) and [here](https://github.com/lusakasa/saka/blob/master/src/suggestion_engine/server/providers/closedTab.js#L29) if tab.incognito is true.

**Comment by jscher2000** [comment] 2018-04-25 03:57
> When querying tabs, Chrome filters incognito tabs while Firefox includes them.

In Chrome, each extension is disabled in incognito by default. If the user enables an extension in incognito, then tabs.query() will return the incognito tabs when run in any tab. I wonder whether users commonly do that?

**Closed** 2018-05-11 01:06 UTC
Labels: bug

**Comment by pureooze** [comment] 2018-05-11 01:26
@jscher2000 I appreciate you taking the time to notify us about this. Thanks 😄
